Repository pyhf/pyhf-tutorial, pull requests merged in 2023-08, with the labels that each got.

#56 docs: Add Computational HEP Traineeship Summer School 2023
  README.md
Labels: documentation

#58 feat: Update to pyhf v0.7.3
  README.md
  binder/requirements.txt
  book/HelloWorld.ipynb
  book/Modifiers.ipynb
  book/SerializationAndPatching.ipynb
  book/SimpleWorkspace.ipynb
  book/WorkspaceManipulations.ipynb
  book/introduction.md
  book/requirements.lock
  lite/jupyterlite.py
Labels: enhancement

#57 doc: Add page describing how to build Upper Limits table
  .gitignore
  binder/requirements.txt
  book/UpperLimitsTable.ipynb
  book/_toc.yml
  book/requirements.lock
Labels: documentation, enhancement

#61 fix: Set notebook cell timeout to 2 minutes
  book/_config.yml
Labels: fix

#64 fix: Use correct model for low stats demonstration
  book/Toys.ipynb
Labels: fix

#65 fix: Update notebook cell timeout for toys notebook
  book/_config.yml
Labels: fix

#66 chore: Set track_progress=True by default
  .github/workflows/deploy-jupyter-book.yml
  book/Toys.ipynb
  book/UsingCalculators.ipynb
Labels: chore, ci
